package com.Flight_reserve.Utilities;

import org.springframework.stereotype.Component;

import java.io.FileOutputStream;
import java.util.Date;


import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

@Component
public class PDFGenerate {
    private static Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18,
            Font.BOLD);
    
    
    private static Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12,
            Font.BOLD);
    
    public  void generatePDF(String filePath, String name,String emailId,String phone,String operatingAirlines,String departureDate,String departureCity) {
        try {
            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream(filePath));
            document.open();
            addMetaData(document);
            addTitleAndTable(document,name,emailId,phone,operatingAirlines,departureCity);
            
            document.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    

	private static void addMetaData(Document document) {
        document.addTitle("My first PDF");
        document.addSubject("Using iText");
        document.addKeywords("Java, PDF, iText");
        document.addAuthor("Lars Vogel");
        document.addCreator("Lars Vogel");
    }
    
    private static void addTitleAndTable(Document document, String name, String emailId, String phone,
			String operatingAirlines, String departureCity)throws DocumentException {
    	 Paragraph preface = new Paragraph();
    	 preface.add(new Paragraph("Flight booking Detatils",catFont));
    	 preface.add(new Paragraph("Report generated by: " + "Flight Reservation Company"+new Date(),smallBold));
    	 document.add(preface);
    	 document.add(Chunk.NEWLINE);
    	 document.add(Chunk.NEWLINE);
    	 
    	 PdfPTable table = new PdfPTable(2);
    	 table.setWidthPercentage(100);
    	 
    	 PdfPCell c1 = new PdfPCell(new Phrase("Passenger Detail"));
    	 c1.setHorizontalAlignment(Element.ALIGN_CENTER);
    	 c1.setColspan(2);
    	 table.addCell(c1);
    	 
    	 table.addCell("Passenger Name");
    	 table.addCell(name);
    	 table.addCell("Email Id");
    	 table.addCell(emailId);
    	 table.addCell("phone Number");
    	 table.addCell(phone);
    	 
    	 document.add(table);
    	 
    	 
    	 PdfPTable table1 = new PdfPTable(2);
    	 table1.setWidthPercentage(100);
    	 
    	 PdfPCell c2 = new PdfPCell(new Phrase("Flight Detail"));
    	 c2.setHorizontalAlignment(Element.ALIGN_CENTER);
    	 c2.setColspan(2);
    	 table1.addCell(c2);
    	 
    	 table1.addCell("Operating Airline");
    	 table1.addCell(operatingAirlines);
    	 table1.addCell("Departure City");
    	 table1.addCell(departureCity);
    	 
    	 
    	 document.add(table1);
    	 document.close();

		
	}
    
}
